In [3]:
pip install --user mlxtend

Collecting mlxtend
  Using cached mlxtend-0.21.0-py2.py3-none-any.whl (1.3 MB)
Requirement already satisfied: setuptools in c:\programdata\anaconda3\lib\site-packages (from mlxtend) (52.0.0.post20210125)
Requirement already satisfied: numpy>=1.16.2 in c:\programdata\anaconda3\lib\site-packages (from mlxtend) (1.20.1)
Requirement already satisfied: pandas>=0.24.2 in c:\programdata\anaconda3\lib\site-packages (from mlxtend) (1.2.4)
Requirement already satisfied: scipy>=1.2.1 in c:\programdata\anaconda3\lib\site-packages (from mlxtend) (1.6.2)
Requirement already satisfied: matplotlib>=3.0.0 in c:\programdata\anaconda3\lib\site-packages (from mlxtend) (3.3.4)
Requirement already satisfied: joblib>=0.13.2 in c:\programdata\anaconda3\lib\site-packages (from mlxtend) (1.0.1)
Collecting scikit-learn>=1.0.2
  Using cached scikit_learn-1.1.2-cp38-cp38-win_amd64.whl (7.3 MB)
Requirement already satisfied: python-dateutil>=2.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.8.1)
Requirement already satisfied: pillow>=6.2.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (8.2.0)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.3.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.4.7)
Requirement already satisfied: six in c:\programdata\anaconda3\lib\site-packages (from cycler>=0.10->matplotlib>=3.0.0->mlxtend) (1.15.0)
Requirement already satisfied: pytz>=2017.3 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2021.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn>=1.0.2->mlxtend) (2.1.0)
Installing collected packages: scikit-learn, mlxtend
Successfully installed mlxtend-0.21.0 scikit-learn-1.1.2
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_table('groceries.csv',header=None)

In [3]:
df

                                                      0
0     citrus fruit,semi-finished bread,margarine,rea...
1                          tropical fruit,yogurt,coffee
2                                            whole milk
3           pip fruit,yogurt,cream cheese ,meat spreads
4     other vegetables,whole milk,condensed milk,lon...
...                                                 ...
9830  sausage,chicken,beef,hamburger meat,citrus fru...
9831                                  cooking chocolate
9832  chicken,citrus fruit,other vegetables,butter,y...
9833  semi-finished bread,bottled water,soda,bottled...
9834  chicken,tropical fruit,other vegetables,vinega...

[9835 rows x 1 columns]

Q2-Total Transactions and items

In [4]:
df.shape[0]

9835

In [5]:
list = []
df[0].map(lambda x : list.append(len(x.split(","))))
print(f"Total items in a datasets are = {max(list)}")

Total items in a datasets are = 32

Q3- Prepare the data for finding transaction set

In [6]:
df[0] = df[0].apply(lambda x : x.split(","))
df

                                                      0
0     [citrus fruit, semi-finished bread, margarine,...
1                      [tropical fruit, yogurt, coffee]
2                                          [whole milk]
3      [pip fruit, yogurt, cream cheese , meat spreads]
4     [other vegetables, whole milk, condensed milk,...
...                                                 ...
9830  [sausage, chicken, beef, hamburger meat, citru...
9831                                [cooking chocolate]
9832  [chicken, citrus fruit, other vegetables, butt...
9833  [semi-finished bread, bottled water, soda, bot...
9834  [chicken, tropical fruit, other vegetables, vi...

[9835 rows x 1 columns]

In [7]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

Q5- Find top selling items with minimum support of 2%

In [8]:
te = TransactionEncoder()
te_ary = te.fit(df[0]).transform(df[0])
df = pd.DataFrame(te_ary, columns=te.columns_)
df

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,baby food,bags,baking powder,bathroom cleaner,beef,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9830,False,False,False,False,False,False,False,False,False,True,...,False,False,False,True,False,False,False,True,False,False
9831,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9832,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
9833,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9834,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False

In [9]:
apriori(df, min_support=0.02,use_colnames = True).sort_values(by = "support" , ascending = False).head()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

     support            itemsets
57  0.255516        (whole milk)
39  0.193493  (other vegetables)
43  0.183935        (rolls/buns)
49  0.174377              (soda)
58  0.139502            (yogurt)

Q6-Find all frequent itemsets with minimum support of 5%.

In [10]:
apriori(df, min_support=0.05,use_colnames = True).sort_values(by = "support")

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

     support                        itemsets
13  0.052364                       (napkins)
0   0.052466                          (beef)
8   0.053279                          (curd)
4   0.055414                        (butter)
30  0.056024            (whole milk, yogurt)
29  0.056634        (whole milk, rolls/buns)
18  0.057651                          (pork)
7   0.058058                        (coffee)
12  0.058566                     (margarine)
10  0.058973                   (frankfurter)
9   0.063447                 (domestic eggs)
3   0.064870                   (brown bread)
25  0.071683            (whipped/sour cream)
11  0.072293         (fruit/vegetable juice)
28  0.074835  (other vegetables, whole milk)
17  0.075648                     (pip fruit)
5   0.077682                   (canned beer)
14  0.079817                    (newspapers)
1   0.080529                  (bottled beer)
6   0.082766                  (citrus fruit)
16  0.088968                        (pastry)
21  0.093950                       (sausage)
22  0.098526                 (shopping bags)
24  0.104931                (tropical fruit)
20  0.108998               (root vegetables)
2   0.110524                 (bottled water)
27  0.139502                        (yogurt)
23  0.174377                          (soda)
19  0.183935                    (rolls/buns)
15  0.193493              (other vegetables)
26  0.255516                    (whole milk)

Q7- Find all frequent itemsets of length 2 with minimum support of 2%.

In [11]:
frequent_itemsets = apriori(df, min_support=0.02, use_colnames=True)
frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))
frequent_itemsets

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

      support                                         itemsets  length
0    0.033452                                       (UHT-milk)       1
1    0.052466                                           (beef)       1
2    0.033249                                        (berries)       1
3    0.026029                                      (beverages)       1
4    0.080529                                   (bottled beer)       1
..        ...                                              ...     ...
117  0.032232                 (whipped/sour cream, whole milk)       2
118  0.020742                     (whipped/sour cream, yogurt)       2
119  0.056024                             (whole milk, yogurt)       2
120  0.023183  (other vegetables, whole milk, root vegetables)       3
121  0.022267           (other vegetables, whole milk, yogurt)       3

[122 rows x 3 columns]

In [12]:
frequent_itemsets[frequent_itemsets['length']==2]

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

      support                           itemsets  length
59   0.021251                 (whole milk, beef)       2
60   0.020437         (whole milk, bottled beer)       2
61   0.024809  (other vegetables, bottled water)       2
62   0.024199        (bottled water, rolls/buns)       2
63   0.028978              (bottled water, soda)       2
..        ...                                ...     ...
115  0.042298       (whole milk, tropical fruit)       2
116  0.029283           (tropical fruit, yogurt)       2
117  0.032232   (whipped/sour cream, whole milk)       2
118  0.020742       (whipped/sour cream, yogurt)       2
119  0.056024               (whole milk, yogurt)       2

[61 rows x 3 columns]

Q8- Find the top 10 association rules with minimum support of 2%, sorted by confidence in descending order

In [13]:
var = apriori(df, min_support=0.02, use_colnames=True)
var = association_rules(var, metric="lift")
var

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(whole milk),(beef),0.255516,0.052466,0.021251,0.083168,1.585180,0.007845,1.033487
1,(beef),(whole milk),0.052466,0.255516,0.021251,0.405039,1.585180,0.007845,1.251315
2,(whole milk),(bottled beer),0.255516,0.080529,0.020437,0.079984,0.993237,-0.000139,0.999408
3,(bottled beer),(whole milk),0.080529,0.255516,0.020437,0.253788,0.993237,-0.000139,0.997684
4,(other vegetables),(bottled water),0.193493,0.110524,0.024809,0.128219,1.160101,0.003424,1.020297
...,...,...,...,...,...,...,...,...,...
129,"(other vegetables, yogurt)",(whole milk),0.043416,0.255516,0.022267,0.512881,2.007235,0.011174,1.528340
130,"(whole milk, yogurt)",(other vegetables),0.056024,0.193493,0.022267,0.397459,2.054131,0.011427,1.338511
131,(other vegetables),"(whole milk, yogurt)",0.193493,0.056024,0.022267,0.115081,2.054131,0.011427,1.066737
132,(whole milk),"(other vegetables, yogurt)",0.255516,0.043416,0.022267,0.087147,2.007235,0.011174,1.047905
133,(yogurt),"(other vegetables, whole milk)",0.139502,0.074835,0.022267,0.159621,2.132979,0.011828,1.100890

In [14]:
var.sort_values(by="confidence" , ascending =False).head(10)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
129,"(other vegetables, yogurt)",(whole milk),0.043416,0.255516,0.022267,0.512881,2.007235,0.011174,1.528340
19,(butter),(whole milk),0.055414,0.255516,0.027555,0.497248,1.946053,0.013395,1.480817
27,(curd),(whole milk),0.053279,0.255516,0.026131,0.490458,1.919481,0.012517,1.461085
123,"(other vegetables, root vegetables)",(whole milk),0.047382,0.255516,0.023183,0.489270,1.914833,0.011076,1.457687
124,"(whole milk, root vegetables)",(other vegetables),0.048907,0.193493,0.023183,0.474012,2.449770,0.013719,1.533320
30,(domestic eggs),(whole milk),0.063447,0.255516,0.029995,0.472756,1.850203,0.013783,1.412030
116,(whipped/sour cream),(whole milk),0.071683,0.255516,0.032232,0.449645,1.759754,0.013916,1.352735
95,(root vegetables),(whole milk),0.108998,0.255516,0.048907,0.448694,1.756031,0.021056,1.350401
53,(root vegetables),(other vegetables),0.108998,0.193493,0.047382,0.434701,2.246605,0.026291,1.426693
35,(frozen vegetables),(whole milk),0.048094,0.255516,0.020437,0.424947,1.663094,0.008149,1.294636

Q9- Find association rules with minimum support of 2% and lift of more than 1.0

In [15]:
var[var['lift']>1]

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(whole milk),(beef),0.255516,0.052466,0.021251,0.083168,1.585180,0.007845,1.033487
1,(beef),(whole milk),0.052466,0.255516,0.021251,0.405039,1.585180,0.007845,1.251315
4,(other vegetables),(bottled water),0.193493,0.110524,0.024809,0.128219,1.160101,0.003424,1.020297
5,(bottled water),(other vegetables),0.110524,0.193493,0.024809,0.224471,1.160101,0.003424,1.039945
6,(bottled water),(rolls/buns),0.110524,0.183935,0.024199,0.218951,1.190373,0.003870,1.044832
...,...,...,...,...,...,...,...,...,...
129,"(other vegetables, yogurt)",(whole milk),0.043416,0.255516,0.022267,0.512881,2.007235,0.011174,1.528340
130,"(whole milk, yogurt)",(other vegetables),0.056024,0.193493,0.022267,0.397459,2.054131,0.011427,1.338511
131,(other vegetables),"(whole milk, yogurt)",0.193493,0.056024,0.022267,0.115081,2.054131,0.011427,1.066737
132,(whole milk),"(other vegetables, yogurt)",0.255516,0.043416,0.022267,0.087147,2.007235,0.011174,1.047905
133,(yogurt),"(other vegetables, whole milk)",0.139502,0.074835,0.022267,0.159621,2.132979,0.011828,1.100890